#!/bin/bash
#
# Licensed to the Gradle Foundation under one or more contributor
# license agreements. See the NOTICE file distributed with this work
# for additional information regarding copyright ownership. The Gradle
# Foundation licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script.
#
#   (2) The JAR on this script is included in the repository.
#
##############################################################################

GRADLE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/gradle"
java -jar "$GRADLE_DIR/gradle-wrapper.jar" "$@"
